/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.15
 * Generated at: 2017-07-13 19:01:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1495991951000L));
    _jspx_dependants.put("jar:file:/home/eits/Área%20de%20Trabalho/Desafio/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Backend/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153395882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("<html >\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <title>Login Form</title>\n");
      out.write("\n");
      out.write("  \n");
      out.write("  \n");
      out.write("<style>\n");
      out.write(".erro\n");
      out.write("{\n");
      out.write("\tcolor: red;\n");
      out.write("\ttext-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write("* { box-sizing:border-box; }\n");
      out.write("\n");
      out.write("body {\n");
      out.write("\tfont-family: Helvetica;\n");
      out.write("\tbackground: #eee;\n");
      out.write("  -webkit-font-smoothing: antialiased;\n");
      out.write("}\n");
      out.write("\n");
      out.write("hgroup { \n");
      out.write("\ttext-align:center;\n");
      out.write("\tmargin-top: 4em;\n");
      out.write("}\n");
      out.write("\n");
      out.write("h1, h3 { font-weight: 300; }\n");
      out.write("\n");
      out.write("h1 { color: #636363; }\n");
      out.write("\n");
      out.write("h3 { color: #4a89dc; }\n");
      out.write("\n");
      out.write("form {\n");
      out.write("\twidth: 380px;\n");
      out.write("\tmargin: 4em auto;\n");
      out.write("\tpadding: 3em 2em 2em 2em;\n");
      out.write("\tbackground: #fafafa;\n");
      out.write("\tborder: 1px solid #ebebeb;\n");
      out.write("\tbox-shadow: rgba(0,0,0,0.14902) 0px 1px 1px 0px,rgba(0,0,0,0.09804) 0px 1px 2px 0px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".group { \n");
      out.write("\tposition: relative; \n");
      out.write("\tmargin-bottom: 45px; \n");
      out.write("}\n");
      out.write("\n");
      out.write("input {\n");
      out.write("\tfont-size: 18px;\n");
      out.write("\tpadding: 10px 10px 10px 5px;\n");
      out.write("\t-webkit-appearance: none;\n");
      out.write("\tdisplay: block;\n");
      out.write("\tbackground: #fafafa;\n");
      out.write("\tcolor: #636363;\n");
      out.write("\twidth: 100%;\n");
      out.write("\tborder: none;\n");
      out.write("\tborder-radius: 0;\n");
      out.write("\tborder-bottom: 1px solid #757575;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input:focus { outline: none; }\n");
      out.write("\n");
      out.write("\n");
      out.write("/* Label */\n");
      out.write("\n");
      out.write("label {\n");
      out.write("\tcolor: #999; \n");
      out.write("\tfont-size: 18px;\n");
      out.write("\tfont-weight: normal;\n");
      out.write("\tposition: absolute;\n");
      out.write("\tpointer-events: none;\n");
      out.write("\tleft: 5px;\n");
      out.write("\ttop: 10px;\n");
      out.write("\t-webkit-transition:all 0.2s ease;\n");
      out.write("\ttransition: all 0.2s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("/* active */\n");
      out.write("\n");
      out.write("input:focus ~ label, input.used ~ label {\n");
      out.write("\ttop: -20px;\n");
      out.write("  -webkit-transform: scale(.75);\n");
      out.write("          transform: scale(.75); left: -2px;\n");
      out.write("\t/* font-size: 14px; */\n");
      out.write("\tcolor: #4a89dc;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("/* Underline */\n");
      out.write("\n");
      out.write(".bar {\n");
      out.write("\tposition: relative;\n");
      out.write("\tdisplay: block;\n");
      out.write("\twidth: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bar:before, .bar:after {\n");
      out.write("\tcontent: '';\n");
      out.write("\theight: 2px; \n");
      out.write("\twidth: 0;\n");
      out.write("\tbottom: 1px; \n");
      out.write("\tposition: absolute;\n");
      out.write("\tbackground: #4a89dc; \n");
      out.write("\t-webkit-transition:all 0.2s ease; \n");
      out.write("\ttransition: all 0.2s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bar:before { left: 50%; }\n");
      out.write("\n");
      out.write(".bar:after { right: 50%; }\n");
      out.write("\n");
      out.write("\n");
      out.write("/* active */\n");
      out.write("\n");
      out.write("input:focus ~ .bar:before, input:focus ~ .bar:after { width: 50%; }\n");
      out.write("\n");
      out.write("\n");
      out.write("/* Highlight */\n");
      out.write("\n");
      out.write(".highlight {\n");
      out.write("\tposition: absolute;\n");
      out.write("\theight: 60%; \n");
      out.write("\twidth: 100px; \n");
      out.write("\ttop: 25%; \n");
      out.write("\tleft: 0;\n");
      out.write("\tpointer-events: none;\n");
      out.write("\topacity: 0.5;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("/* active */\n");
      out.write("\n");
      out.write("input:focus ~ .highlight {\n");
      out.write("\t-webkit-animation: inputHighlighter 0.3s ease;\n");
      out.write("\t        animation: inputHighlighter 0.3s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("/* Animations */\n");
      out.write("\n");
      out.write("@-webkit-keyframes inputHighlighter {\n");
      out.write("\tfrom { background: #4a89dc; }\n");
      out.write("\tto \t{ width: 0; background: transparent; }\n");
      out.write("}\n");
      out.write("\n");
      out.write("@keyframes inputHighlighter {\n");
      out.write("\tfrom { background: #4a89dc; }\n");
      out.write("\tto \t{ width: 0; background: transparent; }\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("/* Button */\n");
      out.write("\n");
      out.write(".button {\n");
      out.write("  position: relative;\n");
      out.write("  display: inline-block;\n");
      out.write("  padding: 12px 24px;\n");
      out.write("  margin: .3em 0 1em 0;\n");
      out.write("  width: 100%;\n");
      out.write("  vertical-align: middle;\n");
      out.write("  color: #fff;\n");
      out.write("  font-size: 16px;\n");
      out.write("  line-height: 20px;\n");
      out.write("  -webkit-font-smoothing: antialiased;\n");
      out.write("  text-align: center;\n");
      out.write("  letter-spacing: 1px;\n");
      out.write("  background: transparent;\n");
      out.write("  border: 0;\n");
      out.write("  border-bottom: 2px solid #3160B6;\n");
      out.write("  cursor: pointer;\n");
      out.write("  -webkit-transition:all 0.15s ease;\n");
      out.write("  transition: all 0.15s ease;\n");
      out.write("}\n");
      out.write(".button:focus { outline: 0; }\n");
      out.write("\n");
      out.write("\n");
      out.write("/* Button modifiers */\n");
      out.write("\n");
      out.write(".buttonBlue {\n");
      out.write("  background: #4a89dc;\n");
      out.write("  text-shadow: 1px 1px 0 rgba(39, 110, 204, .5);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".buttonBlue:hover { background: #357bd8; }\n");
      out.write("\n");
      out.write("\n");
      out.write("/* Ripples container */\n");
      out.write("\n");
      out.write(".ripples {\n");
      out.write("  position: absolute;\n");
      out.write("  top: 0;\n");
      out.write("  left: 0;\n");
      out.write("  width: 100%;\n");
      out.write("  height: 100%;\n");
      out.write("  overflow: hidden;\n");
      out.write("  background: transparent;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("/* Ripples circle */\n");
      out.write("\n");
      out.write(".ripplesCircle {\n");
      out.write("  position: absolute;\n");
      out.write("  top: 50%;\n");
      out.write("  left: 50%;\n");
      out.write("  -webkit-transform: translate(-50%, -50%);\n");
      out.write("          transform: translate(-50%, -50%);\n");
      out.write("  opacity: 0;\n");
      out.write("  width: 0;\n");
      out.write("  height: 0;\n");
      out.write("  border-radius: 50%;\n");
      out.write("  background: rgba(255, 255, 255, 0.25);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".ripples.is-active .ripplesCircle {\n");
      out.write("  -webkit-animation: ripples .4s ease-in;\n");
      out.write("          animation: ripples .4s ease-in;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("/* Ripples animation */\n");
      out.write("\n");
      out.write("@-webkit-keyframes ripples {\n");
      out.write("  0% { opacity: 0; }\n");
      out.write("\n");
      out.write("  25% { opacity: 1; }\n");
      out.write("\n");
      out.write("  100% {\n");
      out.write("    width: 200%;\n");
      out.write("    padding-bottom: 200%;\n");
      out.write("    opacity: 0;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("\n");
      out.write("@keyframes ripples {\n");
      out.write("  0% { opacity: 0; }\n");
      out.write("\n");
      out.write("  25% { opacity: 1; }\n");
      out.write("\n");
      out.write("  100% {\n");
      out.write("    width: 200%;\n");
      out.write("    padding-bottom: 200%;\n");
      out.write("    opacity: 0;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("\n");
      out.write("footer { text-align: center; }\n");
      out.write("\n");
      out.write("footer p {\n");
      out.write("\tcolor: #888;\n");
      out.write("\tfont-size: 13px;\n");
      out.write("\tletter-spacing: .4px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("footer a {\n");
      out.write("\tcolor: #4a89dc;\n");
      out.write("\ttext-decoration: none;\n");
      out.write("\t-webkit-transition:all .2s ease;\n");
      out.write("\ttransition: all .2s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write("footer a:hover {\n");
      out.write("\tcolor: #666;\n");
      out.write("\ttext-decoration: underline;\n");
      out.write("}\n");
      out.write("\n");
      out.write("footer img {\n");
      out.write("\twidth: 80px;\n");
      out.write("\t-webkit-transition:all .2s ease;\n");
      out.write("\ttransition: all .2s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write("footer img:hover { opacity: .83; }\n");
      out.write("\n");
      out.write("footer img:focus , footer a:focus { outline: none; }\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("  \n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<hgroup>\n");
      out.write("\t  <h1>Desafio</h1>\n");
      out.write("\t  <h3>By Wagner Mattei</h3>\n");
      out.write("\t</hgroup>\n");
      out.write("\t<form action=\"./authenticate\" method=\"post\">\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"group\">\n");
      out.write("\t\t\t<input type=\"email\" placeholder=\"E-mail\" name=\"email\"><span class=\"highlight\"></span><span\n");
      out.write("\t\t\t\tclass=\"bar\"></span> \n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"group\">\n");
      out.write("\t\t\t<input type=\"password\" placeholder=\"Senha\" name=\"senha\"><span class=\"highlight\"></span><span\n");
      out.write("\t\t\t\tclass=\"bar\"></span> \n");
      out.write("\t\t</div>\n");
      out.write("\t\t<button type=\"submit\" class=\"button buttonBlue\">\n");
      out.write("\t\t\tLogin\n");
      out.write("\t\t\t<div class=\"ripples buttonRipples\">\n");
      out.write("\t\t\t\t<span class=\"ripplesCircle\"></span>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</button>\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t</form>\n");
      out.write("\n");
      out.write("  \n");
      out.write("  \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/index.jsp(309,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.error != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t<p class=\"erro\">Email ou senha incorretos</p>\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
